# Generated by Django 5.2.5 on 2025-08-25 13:24

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('CV', 'CV / Résumé'), ('CERTIFICATE', 'Certificate'), ('RECOMMENDATION', 'Recommendation Letter'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=uploads.models.upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
