# Generated by Django 5.2.5 on 2025-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('CV', 'CV / Résumé'), ('CERTIFICATE', 'Certificate'), ('RECOMMENDATION', 'Recommendation Letter'), ('PROFILE_IMAGE', 'Profile Image'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
    ]
