# Generated by Django 5.2.5 on 2025-08-27 14:35

import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('CV', 'CV / Résumé'), ('CERTIFICATE', 'Certificate'), ('RECOMMENDATION', 'Recommendation Letter'), ('PROFILE_IMAGE', 'Profile Image'), ('PROJECT', 'Project'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=uploads.models.upload_to),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
